name: Run
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          set -ex

          npm ci
          npx playwright install-deps chromium
          npm run fetch
